modLoader="javafml"
loaderVersion="[32,)"
license="See GitHub repository for details"

[[mods]]
modId="upm"
version="${version}"
displayName="Universal Power Monitor"
authors="superckl"
description="Provides a universal power monitor for monitoring your energy network."

[[dependencies.prayers]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.prayers]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"
